export const AUTH_IN = 'AUTH_IN';
export const AUTH_OUT = 'AUTH_OUT';

export const LOAD_CATEGORIES_REQUEST = 'LOAD_CATEGORIES_REQUEST';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAILED = '_FAILED';

